### ISSUE TITLE
Website: Open Stats

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/joeprevite.com#20]
## Summary

It would be cool to share some stats related to my newsletter, like number of subscribers, average open rate, average clicks, average number of emails sent per month.

### Basic example

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation

Practicing transparency. Aligns with the idea of open source. Good for the community, fun to share :)

**Comment by jsjoeio** [comment]
Something like Lee's [Dashboard page](https://leerob.io/dashboard)

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/3806031/82775978-371b2000-9dfe-11ea-9365-c16a979bf5c9.png">


He even wrote up a blog post on how to do it! 

https://leerob.io/blog/fetching-data-with-swr

**Comment by jsjoeio** [comment]
This will help too: https://leerob.io/blog/real-time-post-views

**Comment by jsjoeio** [comment]
And this 


https://jamstackfns.com/f/firebase

**Comment by jsjoeio** [comment]
I might call it /open like [Nomad List](https://nomadlist.com/open)

**Comment by jsjoeio** [comment]
## Todos 

- [x] Add netlify functions to site
- [x] Get function work in production
- [x] Add firebase
- [x] Add environment variables to Netlify 
- [X] Refactor into other file
- [x] Figure out `accountServiceKey.json`
- [x] Test function to get page views
- [x] Add page views to blog posts
- [x] Add /open page

**Comment by jsjoeio** [comment]
https://www.gatsbyjs.org/blog/2018-12-17-turning-the-static-dynamic/

**Comment by jsjoeio** [comment]
https://github.com/netlify/netlify-lambda/issues/118

**Comment by jsjoeio** [comment]
https://dev.to/jackabox/using-firebase-admin-sdk-with-netlify-lambda-functions-4h8e

**Comment by jsjoeio** [comment]
https://kyleshevlin.com/firebase-and-gatsby-together-at-last

**Comment by jsjoeio** [comment]
Man, I'm struggling hard core with this Firebase part.

**Comment by jsjoeio** [comment]
I think I've run into every error possible...

```js
Error during invocation:  TypeError: i.initStandalone is not a function
```

**Comment by jsjoeio** [comment]
https://joshwcomeau.com/gatsby/netlify-functions-and-gatsby-cloud/#zip-it-and-ship-it

**Comment by jsjoeio** [comment]
man i give up :(

**Comment by jsjoeio** [comment]
[Firebase url](https://console.firebase.google.com/project/website-pageviews-c8d4d/database/website-pageviews-c8d4d/data/~2Fjoeprevite-dot-com)

**Comment by jsjoeio** [comment]
what  day...6 hours of trying.

okay i got basic functions working with netlify. no luck with firebase yet

**Comment by jsjoeio** [comment]
To get the function to work in production:
- I added a `command` to the `build` in the `netlify.toml`
- updated `yarn build` in the `package.json`
- updated the functions directory `functions-build` in the Netlify UI

**Comment by jsjoeio** [comment]
soooo close, I can't get it to work without the JSON file though...

**Comment by jsjoeio** [comment]
I got it working!

Now to try and make it environment variables: https://community.netlify.com/t/using-firebase-admin-sdk-with-lambda-function/2136

**Comment by jsjoeio** [comment]
Using local env with `netlify-lambda`

https://github.com/netlify/netlify-lambda/issues/118

**Comment by jsjoeio** [comment]
FINALLY

**Comment by jsjoeio** [comment]
Closed via #141
